name 'puppet-module-samba'
version '0.0.3'
author 'Spencer Krum'
summary 'Configure samba global paramaters and shares'
description 'Manage samba global configuration and shares as individual resources'
license 'Apache 2'
project_page 'https://github.com/pdxcat/puppet-module-samba'
dependency 'ripienaar/puppet-concat', '0.2.0'
